### ISSUE TITLE
No Space in Device for server in a VM using Hyper-V in windows

### ISSUE THREAD

**Issue by AbdelsalamHaa** [aotuai/brainframe-qt#172]
I faced this issue when I'm trying to install the server side into VM created by Hyper-V 
The error message is attached below 

`failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/python3.6/dist-packages/tensorflow_core/include/google/protobuf/util/internal/expecting_objectwriter.h: no space left on device`

I adjust the hard disk maximum size to be 50 Gb , but it seems like it has to do something with a volume is full.  It is a new created VM so nothing is added besides the requirement for the server side. 

Any idea or suggestion how to solve that, thank  you

**Comment by apockill** [comment]
Hi @AbdelsalamHaa, thank you for Trying out BrainFrame!

Because this repository is for the BrainFrame Client specifically, and this appears to be more of a server question, I went ahead and created a forum post with your question [here](https://forum.aotu.ai/t/no-space-in-device-for-server-in-a-vm-using-hyper-v-in-windows/198). 

Please feel free to follow up on the forum post I created.
